create index if not exists idx_usuarios_perfil on public.usuarios(perfil) where deleted_at is null;
create index if not exists idx_usuarios_ativo on public.usuarios(ativo) where deleted_at is null;
create index if not exists idx_ebaps_status on public.ebaps(status) where deleted_at is null;
create index if not exists idx_equipamentos_ebap on public.equipamentos(ebap_id) where deleted_at is null;
create index if not exists idx_equipamentos_tipo on public.equipamentos(tipo_id) where deleted_at is null;
create index if not exists idx_equipamentos_status on public.equipamentos(status_operacional) where deleted_at is null;
create index if not exists idx_relatorios_diarios_ebap_data on public.relatorios_diarios(ebap_id, data_operacao desc) where deleted_at is null;
create index if not exists idx_relatorios_diarios_status on public.relatorios_diarios(status) where deleted_at is null;
create index if not exists idx_relatorio_secoes_relatorio_ordem on public.relatorio_diario_secoes(relatorio_id, ordem);
create index if not exists idx_relatorio_itens_relatorio on public.relatorio_diario_itens(relatorio_id);
create index if not exists idx_relatorio_itens_equipamento on public.relatorio_diario_itens(equipamento_id);
create index if not exists idx_validacoes_cco_relatorio on public.validacoes_cco(relatorio_id);
create index if not exists idx_validacoes_cco_os on public.validacoes_cco(os_id);
create index if not exists idx_ordens_servico_status on public.ordens_servico(status) where deleted_at is null;
create index if not exists idx_ordens_servico_ebap on public.ordens_servico(ebap_id) where deleted_at is null;
create index if not exists idx_ordens_servico_relatorio on public.ordens_servico(relatorio_id) where deleted_at is null;
create index if not exists idx_ordens_servico_programacao on public.ordens_servico(data_programada, status) where deleted_at is null;
create index if not exists idx_os_historico_os on public.os_historico(os_id, created_at desc);
create index if not exists idx_comentarios_entidade on public.comentarios(entidade_tipo, entidade_id) where deleted_at is null;
create index if not exists idx_anexos_entidade on public.anexos(entidade_tipo, entidade_id) where deleted_at is null;
create index if not exists idx_arquivo_pdf_entidade on public.arquivo_pdf(entidade_tipo, entidade_id) where deleted_at is null;
create index if not exists idx_arquivo_pdf_periodo on public.arquivo_pdf(ano, mes, data_documento desc) where deleted_at is null;
create index if not exists idx_archive_documents_entity on public.archive_documents(entity_type, entity_id) where deleted_at is null;
create index if not exists idx_almox_itens_categoria on public.almoxarifado_itens(categoria) where deleted_at is null;
create index if not exists idx_movimentacoes_item_data on public.movimentacoes_estoque(item_id, created_at desc);
create index if not exists idx_compras_status on public.compras(status) where deleted_at is null;
create index if not exists idx_compras_solicitante on public.compras(solicitante_id) where deleted_at is null;
create index if not exists idx_compra_aprovacoes_compra on public.compra_aprovacoes(compra_id);
create index if not exists idx_contratos_status on public.contratos(status) where deleted_at is null;
create index if not exists idx_financeiro_status_vencimento on public.financeiro_lancamentos(status, vencimento);
create index if not exists idx_medicoes_competencia on public.medicoes(competencia_ano, competencia_mes) where deleted_at is null;
create index if not exists idx_sst_colaboradores_status on public.sst_colaboradores(status) where deleted_at is null;
create index if not exists idx_sst_apr_status on public.sst_apr(status) where deleted_at is null;
create index if not exists idx_sst_epi_ca on public.sst_epi(ca);
create index if not exists idx_sst_epi_entregas_colaborador on public.sst_epi_entregas(colaborador_id, entregue_em desc);
create index if not exists idx_sst_treinamento_colaborador on public.sst_treinamento_colaboradores(colaborador_id, status);
create index if not exists idx_sst_inspecoes_status on public.sst_inspecoes(status) where deleted_at is null;
create index if not exists idx_sst_ocorrencias_status on public.sst_ocorrencias(status) where deleted_at is null;
create index if not exists idx_notificacoes_usuario_lida on public.notificacoes(usuario_id, lida_em, created_at desc);
create index if not exists idx_auditoria_tabela_registro on public.auditoria(tabela, registro_id, created_at desc);
